version: '3'
services:
  jb-nginx-rps:
    image: nginx:alpine
    container_name: jb-nginx-rps
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - jb-home
      - area-quote
  jb-home:
    image: 449788418462.dkr.ecr.ap-southeast-2.amazonaws.com/jb-home:latest
    container_name: jb-home
    expose:
      - "80"
  area-quote:
    image: 449788418462.dkr.ecr.ap-southeast-2.amazonaws.com/area-quote:latest
    container_name: area-quote
    expose:
      - "80"
