version: '3.1'
services:
  jb-nginx-rps:
    image: nginx:alpine
    container_name: jb-nginx-rps
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - jb-home
      - bb-name-generator
      - bbng-ws
  jb-home:
    image: 449788418462.dkr.ecr.ap-southeast-2.amazonaws.com/jb-home:latest
    container_name: jb-home
    expose:
      - "80"
  bb-name-generator:
    image: 449788418462.dkr.ecr.ap-southeast-2.amazonaws.com/bb-name-generator:latest
    container_name: bb-name-generator
    expose:
      - "80"
  bbng-ws:
    image: 449788418462.dkr.ecr.ap-southeast-2.amazonaws.com/bbng-ws:latest
    container_name: bbng-ws
    volumes:
      - /home/administrator/resource/db/bbng.db:/usr/bin/bbng-bed/resources/db/bbng.db
    ports:
      - 8200:8200
