version: '3'
services:
  jb-nginx-rps:
    image: nginx:alpine
    container_name: jb-nginx-rps
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - jb-home
  jb-home:
    image: jb-home:latest
    container_name: jb-home
    expose:
      - "80"
