---
version: 2.1

executors:
  deploy_env:
    docker:
      - image: circleci/python:latest
    working_directory: ~/repo

jobs:
  ansible_deploy:
    executor: deploy_env
    steps:
      - checkout
      - run: ssh-keyscan $SSH_SERVER >> ~/.ssh/known_hosts
      - run: pip install --user ansible
      - run: ~/.local/bin/ansible-playbook -i ~/repo/ansible/inventory.yml ~/repo/ansible/deploy.yml

workflows:
  deploy_stack_update:
    jobs:
      - ansible_deploy

