version: 2.1
jobs:
  deploy:
    docker:
      - image: debian:stretch

    steps:
      - run:
          name: SSH and deploy via script
          command: |
            ssh josh@45.77.237.136 '~/script/deploy.sh'
