---
version: 2.1

executors:
  build_env:
    docker:
      - image: circleci/python:latest
    working_directory: ~/repo

jobs:
  ansible_deploy:
    executor: build_env
    steps:
      - checkout
      - run: pip install --user ansible
      - run: pwd
      - run: ansible-playbook -i ~/jb-nginx-rps/ansible/inventory.yml ~/jb-nginx-rps/ansible/deploy.yml

workflows:
  deploy_stack_update:
    jobs:
      - ansible_deploy

