---
version: 2.1

jobs:
  ansible_deploy:
    docker:
      - image: ansible/ansible:1604
    steps:
      - run:
        name: Install system packages
        command: pip install --upgrade pip && pip install ansible
      - checkout
      - run:
        name: PWD
        command: pwd
      - run:
        name: Execute ansible playbook
        command: ansible-playbook -i ~/jb-nginx-rps/ansible/inventory.yml ~/jb-nginx-rps/ansible/deploy.yml

workflows:
  deploy_stack_update:
    jobs:
      - ansible_deploy

