---
- name: Setup administrator user
  hosts: jbhome
  remote_user: root
  tasks:
    - name: Ensure admin group exists
      group:
        name: admin
        state: present
    - name: Ensure admin group have passwordless sudo access
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%admin'
        line: '%admin ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf%s'
    - name: Add administrator user
      user:
        name: administrator
        group: admin
    - name: Add administrator access key
      authorized_key:
        user: administrator
        state: present
        key: "{{ lookup('file', '/home/josh/.ssh/id_ci_service.pub') }}"
    - name: Check ssh connection as administrator user
      ping:
      remote_user: administrator
